[package]
authors = { workspace = true }
categories = { workspace = true }
description = "Runner for jql - the JSON Query Language tool."
edition = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
name = "jql-runner"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
jql-parser = { path = "../jql-parser", version = "5.2.0" }
rayon = "1.7.0"
serde_json = { workspace = true }
thiserror = { workspace = true }

[lib]
path = "src/lib.rs"
